openapi: 3.1.0
info:
  title: Inventory Service
  version: 1.0.0
paths:
  /inventory:
    get:
      summary: Read Inventory
      description: Uses the get_inventory funciton frominventory.py to return the
        current inventory.
      operationId: read_inventory_inventory_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Modify Inventory
      operationId: modify_inventory_inventory_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    InventoryUpdate:
      properties:
        item:
          type: string
          title: Item
        change:
          type: integer
          title: Change
      type: object
      required:
      - item
      - change
      title: InventoryUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
